<?php
class ISO6391 {
  
  const UEB = ["en"];
  
  // short locale list
  const LA = ['ar','bg','cs','da','de','el','eo','en','es','et','fa','fi','fr','ga','he','hi','hu','id','it','ja','ko','lv','lt','nl','pl','pt','ro','ru','sk','sr','sv','th','tr','vi','zh'];
  
  // 2letter(lang), 3letter(ISO), 4letter(locale), lang name, lang family
  const LANG = [
    ['ab','abk','ab_AB','Abkhazian','Austronesian',TRUE], // ok
    ['aa','   ','aa_AA','Afar',TRUE],
    ['af','   ','af_AF','Afrikaans',TRUE],
    ['ak','   ','ak_AK','Akan',TRUE],
    ['sq','   ','sq_SQ','Albanian',TRUE],
    ['am','   ','am_AM','Amharic',TRUE],
    ['ar','   ','ar_AR','Arabic',TRUE],  // ok
    ['an','   ','an_AN','Aragonese',TRUE],
    ['hy','   ','hy_HY','Armenian',TRUE],
    ['as','   ','as_AS','Assamese',TRUE],
    ['av','   ','av_AV','Avaric',TRUE],
    ['ae','   ','ae_AE','Avestan',TRUE],
    ['ay','   ','ay_AY','Aymara',TRUE],
    ['az','   ','az_AZ','Azerbaijani',TRUE],
    ['bm','   ','bm_BM','Bambara',TRUE],
    ['ba','   ','ba_BA','Bashkir',TRUE],
    ['eu','eu_EU','Basque',TRUE],
    ['be','be_BE','Belarusian',TRUE],
    ['bn','bn_BN','Bengali',TRUE],
    ['bi','bi_BI','Bislama',TRUE],
    ['bs','bs_BS','Bosnian',TRUE],
    ['br','br_BR','Breton',TRUE],
    ['bg','bg_BG','Bulgarian',TRUE],
    ['my','my_MY','Burmese',TRUE],
    ['ca','ca_CA','Catalan',TRUE],
    ['ch','ch_CH','Chamorro',TRUE],
    ['ce','ce_CE','Chechen',TRUE],
    ['ny','ny_NY','Chichewa',TRUE],
    ['zh','zh_CN','Chinese',TRUE],
    ['cv','cv_CV','Chuvash',TRUE],
    ['kw','kw_KW','Cornish',TRUE],
    ['co','co_CO','Corsican',TRUE],
    ['cr','cr_CR','Cree',TRUE],
    ['hr','hr_HR','Croatian',TRUE],
    ['cs','cs_CZ','Czech',TRUE],
    ['da','da_DK','Danish',TRUE],
    ['dv','dv_DV','Divehi',TRUE],
    ['nl','nl_NL','Dutch',TRUE],
    ['dz','dz_DZ','Dzongkha',TRUE],
    ['en','en_US','English',TRUE],
    ['eo','eo_EO','Esperanto',TRUE],
    ['et','et_EE','Estonian',TRUE],
    ['ee','ee_EE','Ewe',TRUE],
    ['fo','fo_FO','Faroese',TRUE],
    ['fj','fj_FJ','Fijian',TRUE],
    ['fi','fi_FI','Finnish',TRUE],
    ['fr','fr_FR','French',TRUE],
    ['fy','fy_FY','Frisian',TRUE],
    ['ff','ff_FF','Fulah',TRUE],
    ['gd','gd_GD','Gaelic',TRUE],
    ['gl','gl_GL','Galician',TRUE],
    ['lg','lg_LG','Ganda',TRUE],
    ['ka','ka_KA','Georgian',TRUE],
    ['de','de_DE','German',TRUE],
    ['el','el_GR','Greek',TRUE],
    ['kl','kl_KL','Kalaallisut',TRUE],
    ['gn','gn_GN','Guarani',TRUE],
    ['gu','gu_GU','Gujarati',TRUE],
    ['ht','ht_HT','Haitian',TRUE],
    ['ha','ha_HA','Hausa',TRUE],
    ['he','he_HE','Hebrew',TRUE],
    ['hz','hz_HZ','Herero',TRUE],
    ['hi','hi_HI','Hindi',TRUE],
    ['ho','ho_HO','Hiri Motu',TRUE],
    ['hu','hu_HU','Hungarian',TRUE],
    ['is','is_IS','Icelandic',TRUE],
    ['io','io_IO','Ido',TRUE],
    ['ig','ig_IG','Igbo',TRUE],
    ['id','id_ID','Indonesian',TRUE],
    ['iu','iu_IU','Inuktitut',TRUE],
    ['ik','ik_IK','Inupiaq',TRUE],
    ['ga','ga_GA','Irish',TRUE],
    ['it','it_IT','Italian',TRUE],
    ['ja','ja_JP','Japanese',TRUE],
    ['jv','jv_JV','Javanese',TRUE],
    ['kn','kn_KN','Kannada',TRUE],
    ['kr','kr_KR','Kanuri',TRUE],
    ['ks','ks_KS','Kashmiri',TRUE],
    ['kk','kk_KK','Kazakh',TRUE],
    ['km','km_KM','Khmer',TRUE],
    ['ki','ki_KI','Kikuyu',TRUE],
    ['rw','rw_RW','Kinyarwanda',TRUE],
    ['ky','ky_KY','Kirghiz',TRUE],
    ['kv','kv_KV','Komi',TRUE],
    ['kg','kg_KG','Kongo',TRUE],
    ['ko','ko_KO','Korean',TRUE],
    ['kj','kj_KJ','Kuanyama',TRUE],
    ['ku','ku_KU','Kurdish',TRUE],
    ['lo','lo_LO','Lao',TRUE],
    ['la','la_LA','Latin',TRUE],
    ['lv','lv_LV','Latvian',TRUE],
    ['li','li_LI','Limburgan',TRUE],
    ['ln','ln_LN','Lingala',TRUE],
    ['lt','lt_LT','Lithuanian',TRUE],
    ['lu','lu_LU','Luba-Katanga',TRUE],
    ['lb','lb_LB','Luxembourgish',TRUE],
    ['mk','mk_MK','Macedonian',TRUE],
    ['mg','mg_MG','Malagasy',TRUE],
    ['ms','ms_MS','Malay',TRUE],
    ['ml','ml_ML','Malayalam',TRUE],
    ['mt','mt_MT','Maltese',TRUE],
    ['gv','gv_GV','Manx',TRUE],
    ['mi','mi_MI','Maori',TRUE],
    ['mr','mr_MR','Marathi',TRUE],
    ['mh','mh_MH','Marshallese',TRUE],
    ['mn','mn_MN','Mongolian',TRUE],
    ['na','na_NA','Nauru',TRUE],
    ['nv','nv_NV','Navajo',TRUE],
    ['nd','nd_ND','Ndebele',TRUE],
    ['ng','ng_NG','Ndonga',TRUE],
    ['ne','ne_NE','Nepali',TRUE],
    ['no','no_NO','Norwegian',TRUE],
    ['ii','ii_II','Sichuan Yi',TRUE],
    ['oc','oc_OC','Occitan',TRUE],
    ['oj','oj_OJ','Ojibwa',TRUE],
    ['or','or_OR','Oriya',TRUE],
    ['om','om_OM','Oromo',TRUE],
    ['os','os_OS','Ossetian',TRUE],
    ['pi','pi_PI','Pali',TRUE],
    ['ps','ps_PS','Pashto',TRUE],
    ['fa','fa_FA','Persian',TRUE],
    ['pl','pl_PL','Polish',TRUE],
    ['pt','pt_PT','Portuguese',TRUE],
    ['pa','pa_PA','Punjabi',TRUE],
    ['qu','qu_QU','Quechua',TRUE],
    ['ro','ro_RO','Romanian',TRUE],
    ['rm','rm_RM','Romansh',TRUE],
    ['rn','rn_RN','Rundi',TRUE],
    ['ru','ru_RU','Russian',TRUE],
    ['se','se_SE','Sami',TRUE],
    ['sm','sm_SM','Samoan',TRUE],
    ['sg','sg_SG','Sango',TRUE],
    ['sa','sa_SA','Sanskrit',TRUE],
    ['sc','sc_SC','Sardinian',TRUE],
    ['sr','sr_SR','Serbian',TRUE],
    ['sn','sn_SN','Shona',TRUE],
    ['sd','sd_SD','Sindhi',TRUE],
    ['si','si_SI','Sinhala',TRUE],
    ['sk','sk_SK','Slovak',TRUE],
    ['sl','sl_SI','Slovenian',TRUE],
    ['so','so_SO','Somali',TRUE],
    ['st','st_ST','Sotho',TRUE],
    ['es','es_ES','Spanish',TRUE],
    ['su','su_SU','Sundanese',TRUE],
    ['sw','sw_SW','Swahili',TRUE],
    ['ss','ss_SS','Swati',TRUE],
    ['sv','sv_SE','Swedish',TRUE],
    ['tl','tl_TL','Tagalog',TRUE],
    ['ty','ty_TY','Tahitian',TRUE],
    ['tg','tg_TG','Tajik',TRUE],
    ['ta','ta_TA','Tamil',TRUE],
    ['tt','tt_TT','Tatar',TRUE],
    ['te','te_TE','Telugu',TRUE],
    ['th','th_TH','Thai',TRUE],
    ['bo','bo_BO','Tibetan',TRUE],
    ['ti','ti_TI','Tigrinya',TRUE],
    ['to','to_TO','Tonga',TRUE],
    ['ts','ts_TS','Tsonga',TRUE],
    ['tn','tn_TN','Tswana',TRUE],
    ['tr','tr_TR','Turkish',TRUE],
    ['tk','tk_TK','Turkmen',TRUE],
    ['tw','tw_TW','Twi',TRUE],
    ['ug','ug_UG','Uighur',TRUE],
    ['uk','uk_UK','Ukrainian',TRUE],
    ['ur','ur_UR','Urdu',TRUE],
    ['uz','uz_UZ','Uzbek',TRUE],
    ['ve','ve_VE','Venda',TRUE],
    ['vi','vi_VI','Vietnamese',TRUE],
    ['vo','vo_VO','Volapük',TRUE],
    ['wa','wa_WA','Walloon',TRUE],
    ['cy','cy_CY','Welsh',TRUE],
    ['wo','wo_WO','Wolof',TRUE],
    ['xh','xh_XH','Xhosa',TRUE],
    ['yi','yi_YI','Yiddish',TRUE],
    ['yo','yo_YO','Yoruba',TRUE],
    ['za','za_ZA','Zhuang',TRUE],
    ['zu','zu_ZU','Zulu',TRUE]
  ];

  // incomplete flags
  const FLAGS = [
    '0'=>'&#x1F1E7; &#x1F1EC; &#127463; &#127468;', // bulg
    '1'=>'&#x1F1E8; &#x1F1F3; &#127464; &#127475;', // chin
    '2'=>'&#x1F1E9; &#x1F1F0; &#127465; &#127472;', // denm
    '3'=>'&#x1F1E9; &#x1F1EA; &#127465; &#127466;', // germ  
    '4'=>'&#x1F1FA; &#x1F1F8; &#127482; &#127480;', // eng
    '5'=>'&#x1F1EA; &#x1F1EA; &#127466; &#127466;', // est
    '6'=>'&#x1F1EB; &#x1F1EE; &#127467; &#127470;', // finn
    '7'=>'&#x1F1EB; &#x1F1F7; &#127467; &#127479;', // franz
    '8'=>'&#x1F1EC; &#x1F1F7; &#127468; &#127479;', // greek
    '9'=>'&#x1F1EE; &#x1F1F9; &#127470; &#127481;', // ita
    '10'=>'&#x1F1EF; &#x1F1F5; &#127471; &#127477;', // jap
    '11'=>'&#x1F1F1; &#x1F1FB; &#127473; &#127483;', // latv
    '12'=>'&#x1F1F1; &#x1F1F9; &#127473; &#127481;', // lit
    '13'=>'&#x1F1F3; &#x1F1F1; &#127475; &#127473;', // durch
    '14'=>'&#x1F1F5; &#x1F1F1; &#127477; &#127473;', // pol
    '15'=>'&#x1F1F5; &#x1F1F9; &#127477; &#127481;', // port
    '16'=>'&#x1F1F7; &#x1F1F4; &#127479; &#127476;', // roman
    '17'=>'&#x1F1F7; &#x1F1FA; &#127479; &#127482;', // russ
    '18'=>'&#x1F1F8; &#x1F1EA; &#127480; &#127466;', // sweed
    '19'=>'&#x1F1F8; &#x1F1F0; &#127480; &#127472;', // slow
    '20'=>'&#x1F1F8; &#x1F1EE; &#127480; &#127470;', // slov
    '21'=>'&#x1F1EA; &#x1F1F8; &#127466; &#127480;', // span
    '22'=>'&#x1F1E8; &#x1F1FF; &#127464; &#127487;', // czeck
    '23'=>'&#x1F1ED; &#x1F1FA; &#127469; &#127482;'  // hunn
  ];
  const COUNTRIES = [
    'AF' => 'Afghanistan',
    'AX' => 'Aland Islands',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AS' => 'American Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarctica',
    'AG' => 'Antigua And Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia And Herzegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet Island',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean Territory',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodia',
    'CM' => 'Cameroon',
    'CA' => 'Canada',
    'CV' => 'Cape Verde',
    'KY' => 'Cayman Islands',
    'CF' => 'Central African Republic',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CN' => 'China',
    'CX' => 'Christmas Island',
    'CC' => 'Cocos (Keeling) Islands',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CG' => 'Congo',
    'CD' => 'Congo, Democratic Republic',
    'CK' => 'Cook Islands',
    'CR' => 'Costa Rica',
    'CI' => 'Cote D\'Ivoire',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Ethiopia',
    'FK' => 'Falkland Islands',
    'FO' => 'Faroe Islands',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'TF' => 'French South.Territories',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard Island & Mcdonald Islands',
    'VA' => 'Holy See (Vatican City State)',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran, Islamic Republic Of',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IM' => 'Isle Of Man',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordan',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'KR' => 'Korea',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Lao Peoples Democratic Republic',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libyan Arab Jamahiriya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MO' => 'Macao',
    'MK' => 'Macedonia',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia, Federated States Of',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands',
    'AN' => 'Netherlands Antilles',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'MP' => 'Northern Mariana Islands',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestinian Territory',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PH' => 'Philippines',
    'PN' => 'Pitcairn',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RE' => 'Reunion',
    'RO' => 'Romania',
    'RU' => 'Russian Federation',
    'RW' => 'Rwanda',
    'BL' => 'Saint Barthelemy',
    'SH' => 'Saint Helena',
    'KN' => 'Saint Kitts And Nevis',
    'LC' => 'Saint Lucia',
    'MF' => 'Saint Martin',
    'PM' => 'Saint Pierre Miquelon',
    'VC' => 'Saint Vincent And Grenadines',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome And Principe',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'GS' => 'South Georgia And Sandwich Isl.',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard And Jan Mayen',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syrian Arab Republic',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania',
    'TH' => 'Thailand',
    'TL' => 'Timor-Leste',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad And Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks And Caicos Islands',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'US' => 'United States',
    'UM' => 'United States Outlying Islands',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VE' => 'Venezuela',
    'VN' => 'Viet Nam',
    'VG' => 'Virgin Islands, British',
    'VI' => 'Virgin Islands, U.S.',
    'WF' => 'Wallis And Futuna',
    'EH' => 'Western Sahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe'
  ];
}
?>
